services:
  fastapi_chat:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: python:3.12-slim
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - DATABASE=${DATABASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHATS_COLLECTION=${CHATS_COLLECTION}
    volumes:
      - ./src:/app  # Mount the Fargate source code
    profiles:
      - fastapi_chat
  # docker compose --env-file .env.dev --profile fastapi_chat up
